### ISSUE TITLE
キー入力による状態遷移機能を実装

### ISSUE THREAD

**Issue by ycums** [ycums/psychic-funicular#40]
﻿## 概要
ここにIssueの概要を書く
What・Whyもここに書くと良いと思う
 
## 変更点

- [x] 入力を Model まで伝搬させる #32 
- [x] ApplicationGroup から Action までのロードができるようにする #41
- [x] 状態遷移のテストをDPGestから移植 #33
- [ ] View に現在のBank の内容を反映する機能を追加 #25
  - [ ] 現在の ApplicationGroup を表示する機能を追加 
  - [ ] ボタンに現在の Bank の内容を表示する機能を追加
  - [ ] ボタンに有効な Entry が割り当てられているときに Enabled にする機能を追加
- [x] Config.LoadBank() の実装
- [x] ボタンの背景色が反映されていない不具合の修正

 
## 追加タスク
- [ ]
- [ ]
- [ ]
 
### 関連課題

---
関連する課題があればここにリンク形式で載せる（Backlog）
 
### 親課題

---
親の課題があればここにリンク形式で載せる（Backlog）
 
#### 備考

---
別途記載する必要があれば書く
